## Import the libraries

In [31]:
import cv2
import numpy as np
import pandas as pd

## Fetch the Data

In [32]:
img = cv2.imread("color.jpg") #Reading the image with opencv
clicked = False
r = g = b = xpos = ypos = 0
print(img.shape)
print(img)

(1362, 1500, 3)
[[[140  41  13]
  [140  41  13]
  [140  41  13]
  ...
  [219 171 143]
  [215 162 135]
  [214 157 131]]

 [[138  39  11]
  [139  40  12]
  [140  41  13]
  ...
  [223 181 152]
  [224 180 151]
  [223 179 150]]

 [[138  39  11]
  [139  40  12]
  [140  41  13]
  ...
  [227 183 154]
  [227 183 154]
  [224 182 153]]

 ...

 [[ 57  47  40]
  [ 57  47  40]
  [ 57  47  40]
  ...
  [ 57  47  40]
  [ 57  47  40]
  [ 57  47  40]]

 [[ 57  47  40]
  [ 57  47  40]
  [ 57  47  40]
  ...
  [ 57  47  40]
  [ 57  47  40]
  [ 57  47  40]]

 [[ 57  47  40]
  [ 57  47  40]
  [ 57  47  40]
  ...
  [ 57  47  40]
  [ 57  47  40]
  [ 57  47  40]]]


## Reading the Color DataSet

In [33]:
index=["color","color_name","hex","R","G","B"]
dataset = pd.read_csv('colors.csv', names=index, header=None)
print(dataset.shape)
dataset.head()

(865, 6)


color             color_name      hex    R    G    B
0    air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1   air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2  air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3       alabama_crimson        Alabama Crimson  #a32638  163   38   56
4            alice_blue             Alice Blue  #f0f8ff  240  248  255

## Function to calculate minimum distance from all colors and get the most matching color

In [34]:
def getColorName(R,G,B):
    minimum = 10000
    for i in range(len(csv)):
        d = abs(R - int(csv.loc[i,"R"])) + abs(G - int(csv.loc[i,"G"]))+ abs(B - int(csv.loc[i,"B"]))
        if(d<=minimum):
            minimum = d
            cname = csv.loc[i,"color_name"]
    return cname

## Function to get Euclidean Coordinates of mouse double click

In [35]:
def draw_function(event, x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        global b,g,r,xpos,ypos, clicked
        clicked = True
        xpos = x
        ypos = y
        b,g,r = img[y,x]
        b = int(b)
        g = int(g)
        r = int(r)

## Start the Program

In [36]:
cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_function)

while(1):

    cv2.imshow("image",img) #Show the image
    if (clicked):
        
        #Draw a rectangle on image
        #cv2.rectangle(image, startpoint, endpoint, color, thickness,-1) fills entire rectangle 
        cv2.rectangle(img,(20,20), (750,60), (b,g,r), -1)

        #Creating text string to display( Color name and RGB values )
        text = getColorName(r,g,b) + ' R='+ str(r) +  ' G='+ str(g) +  ' B='+ str(b)
        
        #cv2.putText(img,text,start,font(0-7),fontScale,color,thickness,lineType )
        cv2.putText(img, text,(50,50),2,0.8,(255,255,255),2,cv2.LINE_AA)

        #For very light colours we will display text in black colour
        if(r+g+b>=600):
            cv2.putText(img, text,(50,50),2,0.8,(0,0,0),2,cv2.LINE_AA)
            
        clicked=False

    #Break the loop when user hits 'esc' key    
    if cv2.waitKey(20) & 0xFF ==27:
        break
    
cv2.destroyAllWindows()